---
- name: postgresql key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present
  become: true

- name: create variable
  command: bash -c "echo \"deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main\" "
  register: repo_line

- debug:
    msg: "{{ repo_line.stdout }}"

- name: add postgresql repo
  apt_repository:
    repo: "{{ repo_line.stdout }}"
    state: present
  become: true

- name: install postgresql
  apt:
    name: "postgresql"
    state: latest
    update_cache: yes
  become: true
